// Random IT joks :)

const mix: string[] = [
  'I changed my password to "incorrect". So whenever I forget what it is the computer will say "Your password is incorrect"',
  'Moses had the first tablet that could connect to the cloud',
  'A clean house is the sign of a broken computer',
  "Why do Java developers wear glasses? Because they don't C#",
  'The first computer dates back to Adam and Eve. It was an Apple with limited memory, just one byte. And then everything crashed',
  'Why are PCs like air conditioners? They stop working properly if you open Windows!',
  'What did the turkey say to the computer? Google, google, google!',
  'There are 10 types of people in this world, those who understand binary and those who dont',
  'What did the robot say to the dead robot? Rust-in-peace',
  'How many programmers does it take to change a light bulb? None, that’s a hardware problem',
  'Why do programmers prefer dark mode? Because light attracts bugs',
  'Why do Python programmers have low self-esteem? Because they’re constantly comparing their self to others',
  'Why do programmers hate nature? It has too many bugs',
  'Why do programmers prefer iOS development? Because Android development is a pain in the app',
  'Why did the developer go broke? Because he used up all his cache',
  'The first computer virus was created in 1983 by Fred Cohen as a proof-of-concept',
  'The first computer was called the ENIAC (Electronic Numerical Integrator and Computer) and was created in 1946',
  'The first 1GB hard drive was announced in 1980, which weighed about 550 pounds and cost $40,000',
  'The first email was sent by Ray Tomlinson to himself in 1971',
  'The first website was created by Tim Berners-Lee and was published on August 6, 1991',
  'The first computer mouse was invented by Douglas Engelbart in 1964 and was made of wood',
  'The first computer game, Spacewar!, was developed in 1962',
  'The first hard disk drive was introduced by IBM in 1956 and could store 5MB of data',
  'The first computer programmer was Ada Lovelace, who wrote an algorithm for Charles Babbage’s early mechanical general-purpose computer',
  'The first computer bug was a real moth found in a computer in 1947',
  'The first laptop was the IBM 5100, released in September 1975',
  'The first computer virus for MS-DOS was called Brain and was created in 1986 and is considered the first computer virus for the IBM PC',
  'The first graphical web browser was called Mosaic and was released in 1993',
  'The first webcam was used at the University of Cambridge to monitor a coffee pot',
  'The first computer to defeat a world champion chess player was IBM’s Deep Blue, which defeated Garry Kasparov in 1997',
  'The first smartphone was IBM’s Simon, released in 1994',
];

export default mix;
